# fly.toml app configuration file generated for sbobine-notify-v2 on 2024-10-19T01:50:10Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sbobine-notify-v2'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[mounts]]
  source = "data"
  destination = "/data"

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
